---
- name: override cassandra.yaml file
  template: src=cassandra.yaml dest=/etc/cassandra/

- name: Set the DC for Cassandra
  lineinfile:
    dest: "/etc/cassandra/cassandra-rackdc.properties"
    regexp: '^dc=.*'
    line: "dc={{ cassandra_dc }}"
  when:
    - cassandra_dc is defined

- name: Set the Rack for Cassandra
  lineinfile:
    dest: "/etc/cassandra/cassandra-rackdc.properties"
    regexp: '^rack=.*'
    line: "rack={{ cassandra_rack }}"
  when:
    - cassandra_rack is defined
