---

- name: CASSANDRA-2356 Workaround
  shell: rm -rf /var/lib/cassandra/*  # noqa 302
  when:
    - cassandra_2356_workaround | bool


- name: remove cassandra-topology properties 
  file: 
    path: /etc/cassandra/cassandra-topology.properties
    state: absent 
