version: '2.4' 
networks:
  cassandra: 
services:
  cass1:
    image: cassandra:4.0    
    container_name: cass1
    hostname: cass1
    
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9042:9042"  
    volumes:
      - ./cassandra_data/data/cass1:/var/lib/cassandra    
      - ./cassandra_data/etc/cass1:/etc/cassandra   
    environment: &environment    
        CASSANDRA_SEEDS: "cass1,cass2"    
        CASSANDRA_CLUSTER_NAME: SolarSystem
        CASSANDRA_DC: Mars
        CASSANDRA_RACK: West
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 128

  cass2:
    image: cassandra:4.0
    container_name: cass2
    hostname: cass2
    
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9043:9042" 
    volumes:
      - ./cassandra_data/data/cass2:/var/lib/cassandra  
      - ./cassandra_data/etc/cass2:/etc/cassandra   
    environment: *environment
    depends_on:
      cass1:    
        condition: service_healthy

  cass3:
    image: cassandra:4.0
    container_name: cass3
    
    hostname: cass3
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9044:9042"  
    volumes:
      - ./cassandra_data/data/cass3:/var/lib/cassandra    
      - ./cassandra_data/etc/cass3:/etc/cassandra    
    environment: *environment    
    depends_on:
      cass2:    
        condition: service_healthy

  cass4:
    image: cassandra:4.0
    container_name: cass4
    hostname: cascass4s3
    
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9045:9042"  
    volumes:
      - ./cassandra_data/data/cass4:/var/lib/cassandra    
      - ./cassandra_data/etc/cass4:/etc/cassandra    
    environment: *environment    
    depends_on:
      cass3:    
        condition: service_healthy
  
  cass5:
    image: cassandra:4.0
    container_name: cass5
    
    hostname: cass5
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9046:9042"  
    volumes:
      - ./cassandra_data/data/cass5:/var/lib/cassandra    
      - ./cassandra_data/etc/cass5:/etc/cassandra    
    environment: *environment    
    depends_on:
      cass4:    
        condition: service_healthy

